#ifndef __LEDBOARD_CONFIG_H__
#define __LEDBOARD_CONFIG_H__

#define LED_BOARD_UNSEEN_HEAD 4 
#define LED_BOARD_HEIGHT 8
#define LED_BOARD_WIDTH 8
#define LED_BOARD_TOTAL_HEIGHT (LED_BOARD_HEIGHT + LED_BOARD_UNSEEN_HEAD + 1)


#define LATCHPIN 3

#define COLUMN_CLOCKPIN 12
#define COLUMN_DATAPIN 11

#define ROW_CLOCKPIN 7
#define ROW_DATAPIN 6

#endif